# azure-pipelines.yml
parameters:
- name: testType
  type: string
  default: smoke
  values:
  - smoke
  - stress

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: |
      docker pull loadimpact/k6
    displayName: Pull k6 image
  - ${{ if eq(parameters.testType, 'stress') }}:
    - script: echo stress
  - ${{ if eq(parameters.testType, 'smoke') }}:
    - script: echo smoke
    displayName: Run k6 cloud