# azure-pipelines.yml
parameters:
- name: testType
  type: string
  values: 'smoke,stress'

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: |
      docker pull loadimpact/k6
    displayName: Pull k6 image
  - ${{ if contains(parameters.testType, 'stress') }}:
  - script: |
      docker run -i \
        -v `pwd`:/src \
        loadimpact/k6 \
        run -e options="stressOptions" /src/003_basic_test/http_get.js \
  - ${{ if contains(parameters.testType, 'smoke') }}:
  - script: |
      docker run -i \
        -v `pwd`:/src \
        loadimpact/k6 \
        run -e options="smokeOptions" /src/003_basic_test/http_get.js \
    displayName: Run k6 cloud